title = "Default configuration for deriving attributions"

device = "mps:0"
seed = 42

[attribution]
target_uid = "determiner_noun_agreement_1"
inference_type = "shapley"
mask_id = ""
n_samples = 300


[model]
name = "bert-base-cased"
layer_count = 12
attention_heads = 12

[paths]
input_dir = "assets/dataset"
tracker_dir = "attributions/trackers"
attribution_path = "attributions/marginal_contributions"
head_mask = "masks"
finetuned_model = "outputs/adapter"

