title = "Default task adapter config"

device = "mps"
seed = 42
dataset_dir = "assets/dataset"
model_name = "bert-base-cased"
metric_name = "accuracy"

wandb.project = "training"
wandb.log_model = "checkpoint"

test_run.size = 100

[preprocess]
input_dir = "assets/blimp"
test_split = 0.1
shuffle = true

[peft]
r = 16
lora_alpha = 16
lora_dropout = 0.1
bias = "all"  # or "lora_only" or "none"

[training]
output_dir = "outputs/adapter"
eval_strategy = "steps"
eval_steps = 5
logging_steps = 5
report_to = "wandb"
per_device_train_batch_size = 32
per_device_eval_batch_size = 32
learning_rate = 5e-5


